version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    restart: always
    volumes:
    - static:/backend_static
    - static:/media
    depends_on:
    - db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    restart: always
    volumes:
      - static:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    restart: always
    ports: 
      - ${OUT_PORT}:80
    volumes:
      - static:/staticfiles/
      - media:/media/